/Users/emilystewartkukwa/Desktop/team-profile-generator/src/generateHTML.js:84             const role = employees.getRole();                                    ^
TypeError: employees.getRole is not a function - error (reminder because I need to step away)